version: "3.5"
services:

  # running nats cluster example: https://gist.github.com/wallyqs/5378f5abcbe4b1b683268cacf2b672d3
  nats:
    ports:
      - "4222:4222"
      - "8222:8222"
    image: nats
    command: "--js --sd /data --tls --tlscert=/config/server-cert.pem --tlskey=/config/server-key.pem --tlscacert=/config/rootCA.pem"
    volumes:
      - ./nats-config:/config
      - ./nats-data:/data

  matchmaker:
    image: matchmaker:latest
    build:
      context: .
      dockerfile: ./bevygap_matchmaker/Dockerfile
    command: --app-name spacepit_server --app-version v0.0.1 --deployment-id dfb7d1868c7f
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    env_file:
      - .matchmaker.env
