#!/bin/bash -ex
wget https://api.edgegap.com/swagger.json -O swagger.json
echo "PWD=$PWD"
docker run \
	--rm -v $PWD:/local openapitools/openapi-generator-cli generate \
	-i /local/swagger.json -g rust -o /local/edgegap_async/ --additional-properties=packageName=edgegap_async,packageVersion=0.1.0
rm swagger.json
# Autogenerated description field is too long for crates.io, tidy up the cargo file.
#  sed -i for in-place editing behaves differently on different OSes, so we use a temp file.
cd edgegap_async
cat Cargo.toml | \
	sed -e 's/^description =.*$/description = "Auto-generated client library for the Edgegap API (async), used by bevygap"/' \
	    -e '/^description.*/a \
repository = "https://github.com/RJ/bevygap/"' > Cargo.toml.publish \
	&& rm Cargo.toml && mv Cargo.toml.publish Cargo.toml
